apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: opspulse-api
    newName: nurud43/opspulse-api
    newTag: v0.1.5
  - name: opspulse-web
    newName: nurud43/opspulse-web
    newTag: v0.1.5
replicas:
  - name: opspulse-api
    count: 2
  - name: opspulse-web
    count: 2
patches:
  - path: patches/bare-metal-labels.yaml
