apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - api/rbac.yaml
  - api/configmap.yaml
  - api/deployment.yaml
  - api/service.yaml
  - web/configmap.yaml
  - web/deployment.yaml
  - web/service.yaml
  - servicemonitor.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      opspulse.io/gitops-managed: "true"
