apiVersion: v1
kind: Namespace
metadata:
  name: opspulse
  labels:
    app.kubernetes.io/name: opspulse
    app.kubernetes.io/part-of: bare-metal-kubernetes-reliability-platform
    opspulse.io/gitops-managed: "true"
