apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homepi
      containers:
        - name: argocd-server
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homepi
      containers:
        - name: argocd-repo-server
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homepi
      containers:
        - name: redis
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: homepi
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
