apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: bare-metal-kubernetes-reliability-platform
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.11.1
      helm:
        releaseName: alloy
        valueFiles:
          - $values/platform/logging/alloy-values.yaml
    - repoURL: git@github.com:mo-abdulai/bare-metal-kubernetes-reliability-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
