apiVersion: v1
kind: ConfigMap
metadata:
  name: opspulse-api-config
  namespace: opspulse
  labels:
    app.kubernetes.io/name: opspulse-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bare-metal-kubernetes-reliability-platform
data:
  APP_NAME: "OpsPulse API"
  APP_VERSION: "0.1.0"
  ENVIRONMENT: "bare-metal"
  PLATFORM_NAME: "Bare-Metal Kubernetes Reliability & Operations Platform"
