apiVersion: v1
kind: Service
metadata:
  name: opspulse-api
  namespace: opspulse
  labels:
    app: opspulse-api
    app.kubernetes.io/name: opspulse-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bare-metal-kubernetes-reliability-platform
spec:
  type: ClusterIP
  selector:
    app: opspulse-api
  ports:
    - name: http
      port: 8000
      targetPort: http
